name: "Release"

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"
          cache: "npm"
      - name: Install dependencies
        run: npm ci
      - name: Build and package
        run: npm run prepare
      - name: Verify build
        run: npm run verify
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/index.js
            dist/main.js
            dist/licenses.txt
            action.yml
            create-main.js
            verify-build.js
          body: |
            Release ${{ github.ref_name }}

            Automatically created by the release workflow.
