name: Review Bot

on:
  pull_request:
    types: [opened, edited, synchronize]

# Add permissions for reviewing PRs
permissions:
  contents: read
  pull-requests: write

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Review Bot
        uses: aleksbanks/review-bot-action@v1.7
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
